package com.example.secure_notes.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import com.fasterxml.jackson.annotation.JsonIgnore;

/*
 * Entity class representing a note. Maps to the "notes" table in the database. 
 * Stores encrypted note data associated with a specific user. 
 * 
 * Database Mapping:
 *  Table name: "notes"
 *  Primary key: Auto-generated ID
 *  Foreign key: user_id (references users table)
 * 
 * Security Features:
 *  Content stores AES-256 encrypted data
 *  Each note is owned by exactly one user
 *  User reference is hidden from JSON serialization
 * 
 * Relationships:
 *  Many-to-one with User entity
 */

@Entity
@Table(name = "notes")
public class Note {

    /*
     * The unique identifier for the note. Auto-generated by the database. 
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
     * The title of the note.
     */
    @Column(nullable = false)
    private String title;

    /*
     * The encrypted content of the note. 
     * 
     * Security: Always contains AES-256 encrypted data
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content; 

    /*
     * The user who owns this note. Represents the many-to-one relationship between notes
     * and users. 
     * 
     * Foreign key: user_id in the notes table.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnore
    private User user;

    /*
     * The timestamp when the note was created.
     */
    private LocalDateTime timeCreated;

    /*
     * The timesttamp when the note was last updated. 
     */
    private LocalDateTime timeUpdated;

    /*
     * Default constructor required by JPA. Creates an empty Note instance. 
     */
    public Note() {
    }

    /*
     * Full constructor for creating a Note with all fields. 
     * 
     * @param id the unique identifier for the note
     * @param title the title of the note (required, plaintext)
     * @param content the encrypted content of the note (required, AES-256 encrypted)
     * @param user the user who owns this note (required)
     * @param timeCreated the timestamp when the note was created
     * @param timeUpdated the timestamp when the note was updated
     */
    public Note(Long id, String title, String content, User user, LocalDateTime timeCreated, LocalDateTime timeUpdated) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.user = user;
        this.timeCreated = timeCreated;
        this.timeUpdated = timeUpdated;
    }

    /*
     * Gets the unique identifier for this note.
     * 
     * @return the note's ID
     */
    public Long getId() {
    return id;
    }

    /*
     * Sets the unique identifier for this note.
     * 
     * Note: this is typically set automatically by the database.
     * 
     * @param id the Note's ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /*
     * Gets the title of this note.
     * 
     * @return the note's title
     */
    public String getTitle() {
        return title;
    }

    /*
     * Sets the title of this note. 
     * 
     * @param title the title to set (required)
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /*
     * Gets the encrypted content of this note. 
     * 
     * @return the AES-256 encrypted content
     */
    public String getContent() {
        return content;
    }

    /*
     * Sets the encrypted content of this note. 
     * 
     * @param content the AES-256 encrypted content to set (required)
     */
    public void setContent(String content) {
        this.content = content;
    }

    /* 
     * Gets the user who owns this note.
     * 
     * @return the note's owner
     * @throws LazyInitializationException if accessed outside of a 
     *  transaction and the user hasn't been eagerly loaded. 
    */
    public User getUser() {
        return user;
    }

    /*
     * Sets the user who owns this note. 
     * 
     * This establishes the relationshi etween the note and its owner. 
     * 
     * @param user the user to set as the owner (required)
     */
    public void setUser(User user) {
        this.user = user;
    }

    /*
     * Gets the timestam when this note was created. 
     * 
     * @return the creation timestamp
     */
    public LocalDateTime getTimeCreated() {
        return timeCreated;
    }

    /*
     * Sets the creation timestamp for this note.
     * 
     * This should typically be set once when the note is first 
     *  created and should not be modified afterwards.
     * 
     * @param timeCreated the creation timeestamp. 
     */
    public void setTimeCreated(LocalDateTime timeCreated) {
        this.timeCreated = timeCreated;
    }

    /*
     * Gets the timestamp when this note was last updated.
     * 
     * @return the last update timestamp
     */
    public LocalDateTime getTimeUpdated() {
        return timeUpdated;
    }

    /*
     * Sets the timestamp for when this note was last updated. 
     * 
     * This should be updated whenever the note's title or content ismodified.
     * The service layer should handle setting this timestamp during update operations. 
     * 
     * @param timeUpdated the last update timestamp
     */
    public void setTimeUpdated(LocalDateTime timeUpdated) {
        this.timeUpdated = timeUpdated;
    }
    
}
