package com.example.secure_notes.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.List;
import java.util.ArrayList;
import com.fasterxml.jackson.annotation.JsonIgnore;

/* Entity class representing a user in the notes application. 
 * 
 * This class maps to the users table in the dtabase and stores user authentication
 * information, roles, and associated notes. Each user can have multiple roles and can own multiple notes.
 * 
 * Database Mapping:
 *  Table Name: "users"
 *  Primary key: aut-generated ID
 *  Unique constraints: username, email
 * 
 * Relationships:
 *  One-to-Many with Note entities
 *  Roles stored as an element collection
*/

@Entity
@Table(name = "users")
public class User {

    /*
     * The unique identifier for the user. Auto-generated by the database. 
     * Primary key. 
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /*
     * The unique username for the user.  
     */
    @Column(unique = true, nullable = false)
    private String username;
    /*
     * The email address of the user. Optional but must be unique if provided. 
     */
    @Column(unique = true, nullable = true)
    private String email;
    /*
     * The hashed password for the user. 
     */
    @Column(nullable = false)
    private String passwordHash;
    /*
     * The set of roles assigned to the user. Stored as strings (e.g., "ROLE_USER", "ROLE_ADMIN")
     */
    @ElementCollection(fetch = FetchType.EAGER)
    private Set<String> roles = new HashSet<>();

    /*
     * The list of notes owned by this user. Represents the one-to-many relationship
     * between suers and notes. When a user is deleted, all associated notes are automatically
     * deleted due to the cascade and orphan removal settings. 
    */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnore
    private List<Note> notes = new ArrayList<>();

    /* 
     * The timestamp when the user account was created. Automatically set when the entity 
     * is first persisted to the database. 
    */
    private LocalDateTime timeCreated;

    /*
     * Default constructor required by JPA.
     */
    public User() {
    }

    /*Full constructor for creating a User with all fields. 
     * 
     * @param id the unique identifier for the user
     * @param username the uniqu username(required)
     * @param email the email address (optional, must be unique if provided)
     * @param passwordHash the hashed password (required)
     * @param roles the set of roles assigned to the user
     * @param notes the list of ntoes owned by the user
     * @param timeCreated the timestamp when the user was created
     */
    public User(Long id, String username, String email, String passwordHash, Set<String> roles, List<Note> notes, LocalDateTime timeCreated) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.passwordHash = passwordHash;
        this.roles = roles;
        this.notes = notes;
        this.timeCreated = timeCreated;
    }
    /*
     * Gets the unique identifier for this user.
     * 
     * @return the user's ID
     */
    public Long getId() {
        return id;
    }

    /*
     * Sets the unique identifier for this user.
     * 
     * @param id the user's ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /*
     * Gets the user's username
     * 
     * @return username 
     */
    public String getUsername() {
        return username;
    }

    /*
     * Sets the user's username.
     * 
     * @param username (required, must be unique)
     * @throws PersistenceException if username is not unique
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /*
     * Gets the email for this user.
     * 
     * @return the email address
     */
    public String getEmail() {
        return email;
    }

    /*
     * Sets the email address for this user. 
     * 
     * @param email (optional, must be unique if provided)
     * @throws PErsistenceExcetion if email is not unique. 
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /*
     * Gets the hashed password for this user. 
     * 
     * @return the hashed password
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /*
     * Sets the hashed password for this user. 
     * 
     * Important: Always hash the password before calling this method. 
     * 
     * @param passwordHash the hashed password to set (required)
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /*
     * Gets the set of roles assigned to this user. 
     * 
     * @return the set of roles
     */
    public Set<String> getRoles() {
        return roles;
    }

    /*
     * Sets the roles for this user. 
     * 
     * @param roles the set of roles to assign
     */
    public void setRoles(Set<String> roles) {
        this.roles = roles;
    }

    /*
     * Gets the list of notes owned by this user. 
     * 
     * @return the list of notes
     */
    public List<Note> getNotes() {
        return notes;
    }

    /*
     * Sets the list of notes owned by this user. 
     * 
     * @param notes the list of notes to set. 
     */
    public void setNotes(List<Note> notes) {
        this.notes = notes;
    }

    /*
     * Gets the timestamp when this user account was created. 
     * 
     * @return the creation timestamp
     */
    public LocalDateTime getTimeCreated() {
        return timeCreated;
    }

    /*
     * Sets the creation timestamp for this user. 
     * 
     * Note: this is typically set automatically.
     * 
     * @param timeCreated the creation timestamp.
     */
    public void setTimeCreated(LocalDateTime timeCreated) {
        this.timeCreated = timeCreated;
    }

    /*
     * JPA lifecycle callback method invoked before the entity is persisted. 
     * 
     * Automatically sets the timeCreated field to the current timestamp when the user
     * is first saved to the database. 
     * 
     * Note: This method is called by JPA and should not be invoked directly by application code. 
     */
    @PrePersist
    protected void onCreate() {
        this.timeCreated = LocalDateTime.now();
    }


}
